seqtk sample -s 1 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaaa
seqtk sample -s 2 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaab
seqtk sample -s 3 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaac
seqtk sample -s 4 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaad
seqtk sample -s 5 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaae
seqtk sample -s 6 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaaf
seqtk sample -s 7 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaag
seqtk sample -s 8 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaah
seqtk sample -s 9 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaai
seqtk sample -s 10 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaaj
seqtk sample -s 11 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaak
seqtk sample -s 12 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaal
seqtk sample -s 13 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaam
seqtk sample -s 14 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaan
seqtk sample -s 15 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaao
seqtk sample -s 16 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaap
seqtk sample -s 17 ~/publicData/ncbi/refseq/viral/viral.123.all.genomic.fna 2 > genome.test.fnaaq
